request_adapters:
- default_planner_request_adapters/AddTimeParameterization
- default_planner_request_adapters/FixWorkspaceBounds
- default_planner_request_adapters/FixStartStateBounds
- default_planner_request_adapters/FixStartStateCollision
- default_planner_request_adapters/FixStartStatePathConstraints

inbound:
  boxes:
  - {name: "box1", frame: "table", position: [0.423, 0.394, 1.1], quaternion: [0, 1, 0, 0], heigth: 0.1}
  - {name: "box2", frame: "table", position: [0.85, 0.37, 1.1], quaternion: [0, 1, 0, 0], heigth: 0.1}
  #- Translation: [-0.038, 0.235, 0.985]
  #- Rotation: in Quaternion [-0.010, 0.996, 0.092, 0.000]


  objects:
  - type: "type1"
    box: "box1"

    grasp_poses:
    - {tool: "tip", position: [0.423, 0.394, 1.1], quaternion: [0, 1, 0, 0]}

  - type: "type1"
    box: "box2"

    grasp_poses:
    - {tool: "tip", position: [0.85, 0.37, 1.1], quaternion: [0, 1, 0, 0]}

