string location_id
---
int8 result
int8 SceneError=-1
int8 NoAvailableTrajectories=-2
int8 TrajectoryError=-3
int8 NotInitialized=-4
int8 Success=0

duration expected_duration
duration actual_duration
int32 trials
float64 hrc_overhead
float64 estimated_hrc_overhead
---
int8 phase
int8 GoingToLocation=1
