// Generated by gencpp from file manipulation_msgs/AddObjectsRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDOBJECTSREQUEST_H
#define MANIPULATION_MSGS_MESSAGE_ADDOBJECTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <manipulation_msgs/Object.h>

namespace manipulation_msgs
{
template <class ContainerAllocator>
struct AddObjectsRequest_
{
  typedef AddObjectsRequest_<ContainerAllocator> Type;

  AddObjectsRequest_()
    : inbound_box_name()
    , add_objects()  {
    }
  AddObjectsRequest_(const ContainerAllocator& _alloc)
    : inbound_box_name(_alloc)
    , add_objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _inbound_box_name_type;
  _inbound_box_name_type inbound_box_name;

   typedef std::vector< ::manipulation_msgs::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::manipulation_msgs::Object_<ContainerAllocator> >::other >  _add_objects_type;
  _add_objects_type add_objects;





  typedef boost::shared_ptr< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddObjectsRequest_

typedef ::manipulation_msgs::AddObjectsRequest_<std::allocator<void> > AddObjectsRequest;

typedef boost::shared_ptr< ::manipulation_msgs::AddObjectsRequest > AddObjectsRequestPtr;
typedef boost::shared_ptr< ::manipulation_msgs::AddObjectsRequest const> AddObjectsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'manipulation_msgs': ['/home/jacobi/projects/ros_ws/src/manipulation/matlab_msg_gen_ros1/glnxa64/src/manipulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9463f0128c5814412de7904bb976146";
  }

  static const char* value(const ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9463f0128c58144ULL;
  static const uint64_t static_value2 = 0x12de7904bb976146ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation_msgs/AddObjectsRequest";
  }

  static const char* value(const ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string inbound_box_name\n"
"manipulation_msgs/Object[] add_objects\n"
"\n"
"================================================================================\n"
"MSG: manipulation_msgs/Object\n"
"manipulation_msgs/Grasp[] grasping_poses\n"
"string type\n"
"string id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: manipulation_msgs/Grasp\n"
"geometry_msgs/Pose pose\n"
"string tool_name\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inbound_box_name);
      stream.next(m.add_objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddObjectsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation_msgs::AddObjectsRequest_<ContainerAllocator>& v)
  {
    s << indent << "inbound_box_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.inbound_box_name);
    s << indent << "add_objects[]" << std::endl;
    for (size_t i = 0; i < v.add_objects.size(); ++i)
    {
      s << indent << "  add_objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::manipulation_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.add_objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDOBJECTSREQUEST_H
