// Generated by gencpp from file pickplace_msgs/ListOfObjectsResponse.msg
// DO NOT EDIT!


#ifndef PICKPLACE_MSGS_MESSAGE_LISTOFOBJECTSRESPONSE_H
#define PICKPLACE_MSGS_MESSAGE_LISTOFOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pickplace_msgs/PickBox.h>

namespace pickplace_msgs
{
template <class ContainerAllocator>
struct ListOfObjectsResponse_
{
  typedef ListOfObjectsResponse_<ContainerAllocator> Type;

  ListOfObjectsResponse_()
    : inbound_boxes()  {
    }
  ListOfObjectsResponse_(const ContainerAllocator& _alloc)
    : inbound_boxes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::pickplace_msgs::PickBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pickplace_msgs::PickBox_<ContainerAllocator> >::other >  _inbound_boxes_type;
  _inbound_boxes_type inbound_boxes;





  typedef boost::shared_ptr< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListOfObjectsResponse_

typedef ::pickplace_msgs::ListOfObjectsResponse_<std::allocator<void> > ListOfObjectsResponse;

typedef boost::shared_ptr< ::pickplace_msgs::ListOfObjectsResponse > ListOfObjectsResponsePtr;
typedef boost::shared_ptr< ::pickplace_msgs::ListOfObjectsResponse const> ListOfObjectsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pickplace_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'pickplace_msgs': ['/home/jacobi/projects/ros_ws/src/manipulation/matlab_msg_gen_ros1/glnxa64/src/pickplace_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a03ffd681ce57fde2c5f01b0609f939";
  }

  static const char* value(const ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a03ffd681ce57fdULL;
  static const uint64_t static_value2 = 0xe2c5f01b0609f939ULL;
};

template<class ContainerAllocator>
struct DataType< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pickplace_msgs/ListOfObjectsResponse";
  }

  static const char* value(const ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pickplace_msgs/PickBox[] inbound_boxes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pickplace_msgs/PickBox\n"
"pickplace_msgs/Object[] objects\n"
"string name\n"
"geometry_msgs/Pose approach_pose\n"
"\n"
"================================================================================\n"
"MSG: pickplace_msgs/Object\n"
"pickplace_msgs/Grasp[] grasping_poses\n"
"string type\n"
"string id\n"
"\n"
"================================================================================\n"
"MSG: pickplace_msgs/Grasp\n"
"geometry_msgs/Pose pose\n"
"string tool_name\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inbound_boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListOfObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pickplace_msgs::ListOfObjectsResponse_<ContainerAllocator>& v)
  {
    s << indent << "inbound_boxes[]" << std::endl;
    for (size_t i = 0; i < v.inbound_boxes.size(); ++i)
    {
      s << indent << "  inbound_boxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pickplace_msgs::PickBox_<ContainerAllocator> >::stream(s, indent + "    ", v.inbound_boxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICKPLACE_MSGS_MESSAGE_LISTOFOBJECTSRESPONSE_H
