// Generated by gencpp from file pickplace_msgs/ListOfObjects.msg
// DO NOT EDIT!


#ifndef PICKPLACE_MSGS_MESSAGE_LISTOFOBJECTS_H
#define PICKPLACE_MSGS_MESSAGE_LISTOFOBJECTS_H

#include <ros/service_traits.h>


#include <pickplace_msgs/ListOfObjectsRequest.h>
#include <pickplace_msgs/ListOfObjectsResponse.h>


namespace pickplace_msgs
{

struct ListOfObjects
{

typedef ListOfObjectsRequest Request;
typedef ListOfObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListOfObjects
} // namespace pickplace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pickplace_msgs::ListOfObjects > {
  static const char* value()
  {
    return "0a03ffd681ce57fde2c5f01b0609f939";
  }

  static const char* value(const ::pickplace_msgs::ListOfObjects&) { return value(); }
};

template<>
struct DataType< ::pickplace_msgs::ListOfObjects > {
  static const char* value()
  {
    return "pickplace_msgs/ListOfObjects";
  }

  static const char* value(const ::pickplace_msgs::ListOfObjects&) { return value(); }
};


// service_traits::MD5Sum< ::pickplace_msgs::ListOfObjectsRequest> should match 
// service_traits::MD5Sum< ::pickplace_msgs::ListOfObjects > 
template<>
struct MD5Sum< ::pickplace_msgs::ListOfObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pickplace_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::ListOfObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pickplace_msgs::ListOfObjectsRequest> should match 
// service_traits::DataType< ::pickplace_msgs::ListOfObjects > 
template<>
struct DataType< ::pickplace_msgs::ListOfObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::pickplace_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::ListOfObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pickplace_msgs::ListOfObjectsResponse> should match 
// service_traits::MD5Sum< ::pickplace_msgs::ListOfObjects > 
template<>
struct MD5Sum< ::pickplace_msgs::ListOfObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pickplace_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::ListOfObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pickplace_msgs::ListOfObjectsResponse> should match 
// service_traits::DataType< ::pickplace_msgs::ListOfObjects > 
template<>
struct DataType< ::pickplace_msgs::ListOfObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::pickplace_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::ListOfObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICKPLACE_MSGS_MESSAGE_LISTOFOBJECTS_H
