# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from manipulation_msgs/Location.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Location(genpy.Message):
  _md5sum = "bb54b8ed93f2e9fcc9305e900eda57dd"
  _type = "manipulation_msgs/Location"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string id
string frame
geometry_msgs/Pose pose
geometry_msgs/Pose approach_relative_pose
geometry_msgs/Pose return_relative_pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['id','frame','pose','approach_relative_pose','return_relative_pose']
  _slot_types = ['string','string','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,frame,pose,approach_relative_pose,return_relative_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Location, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = ''
      if self.frame is None:
        self.frame = ''
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.approach_relative_pose is None:
        self.approach_relative_pose = geometry_msgs.msg.Pose()
      if self.return_relative_pose is None:
        self.return_relative_pose = geometry_msgs.msg.Pose()
    else:
      self.id = ''
      self.frame = ''
      self.pose = geometry_msgs.msg.Pose()
      self.approach_relative_pose = geometry_msgs.msg.Pose()
      self.return_relative_pose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_21d().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.approach_relative_pose.position.x, _x.approach_relative_pose.position.y, _x.approach_relative_pose.position.z, _x.approach_relative_pose.orientation.x, _x.approach_relative_pose.orientation.y, _x.approach_relative_pose.orientation.z, _x.approach_relative_pose.orientation.w, _x.return_relative_pose.position.x, _x.return_relative_pose.position.y, _x.return_relative_pose.position.z, _x.return_relative_pose.orientation.x, _x.return_relative_pose.orientation.y, _x.return_relative_pose.orientation.z, _x.return_relative_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.approach_relative_pose is None:
        self.approach_relative_pose = geometry_msgs.msg.Pose()
      if self.return_relative_pose is None:
        self.return_relative_pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8')
      else:
        self.id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame = str[start:end].decode('utf-8')
      else:
        self.frame = str[start:end]
      _x = self
      start = end
      end += 168
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.approach_relative_pose.position.x, _x.approach_relative_pose.position.y, _x.approach_relative_pose.position.z, _x.approach_relative_pose.orientation.x, _x.approach_relative_pose.orientation.y, _x.approach_relative_pose.orientation.z, _x.approach_relative_pose.orientation.w, _x.return_relative_pose.position.x, _x.return_relative_pose.position.y, _x.return_relative_pose.position.z, _x.return_relative_pose.orientation.x, _x.return_relative_pose.orientation.y, _x.return_relative_pose.orientation.z, _x.return_relative_pose.orientation.w,) = _get_struct_21d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_21d().pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.approach_relative_pose.position.x, _x.approach_relative_pose.position.y, _x.approach_relative_pose.position.z, _x.approach_relative_pose.orientation.x, _x.approach_relative_pose.orientation.y, _x.approach_relative_pose.orientation.z, _x.approach_relative_pose.orientation.w, _x.return_relative_pose.position.x, _x.return_relative_pose.position.y, _x.return_relative_pose.position.z, _x.return_relative_pose.orientation.x, _x.return_relative_pose.orientation.y, _x.return_relative_pose.orientation.z, _x.return_relative_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.approach_relative_pose is None:
        self.approach_relative_pose = geometry_msgs.msg.Pose()
      if self.return_relative_pose is None:
        self.return_relative_pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.id = str[start:end].decode('utf-8')
      else:
        self.id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.frame = str[start:end].decode('utf-8')
      else:
        self.frame = str[start:end]
      _x = self
      start = end
      end += 168
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.approach_relative_pose.position.x, _x.approach_relative_pose.position.y, _x.approach_relative_pose.position.z, _x.approach_relative_pose.orientation.x, _x.approach_relative_pose.orientation.y, _x.approach_relative_pose.orientation.z, _x.approach_relative_pose.orientation.w, _x.return_relative_pose.position.x, _x.return_relative_pose.position.y, _x.return_relative_pose.position.z, _x.return_relative_pose.orientation.x, _x.return_relative_pose.orientation.y, _x.return_relative_pose.orientation.z, _x.return_relative_pose.orientation.w,) = _get_struct_21d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_21d = None
def _get_struct_21d():
    global _struct_21d
    if _struct_21d is None:
        _struct_21d = struct.Struct("<21d")
    return _struct_21d
