// Generated by gencpp from file pickplace_msgs/AddRemoveObjects.msg
// DO NOT EDIT!


#ifndef PICKPLACE_MSGS_MESSAGE_ADDREMOVEOBJECTS_H
#define PICKPLACE_MSGS_MESSAGE_ADDREMOVEOBJECTS_H

#include <ros/service_traits.h>


#include <pickplace_msgs/AddRemoveObjectsRequest.h>
#include <pickplace_msgs/AddRemoveObjectsResponse.h>


namespace pickplace_msgs
{

struct AddRemoveObjects
{

typedef AddRemoveObjectsRequest Request;
typedef AddRemoveObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddRemoveObjects
} // namespace pickplace_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pickplace_msgs::AddRemoveObjects > {
  static const char* value()
  {
    return "d10a1cb92c62629deb4db3c775937bac";
  }

  static const char* value(const ::pickplace_msgs::AddRemoveObjects&) { return value(); }
};

template<>
struct DataType< ::pickplace_msgs::AddRemoveObjects > {
  static const char* value()
  {
    return "pickplace_msgs/AddRemoveObjects";
  }

  static const char* value(const ::pickplace_msgs::AddRemoveObjects&) { return value(); }
};


// service_traits::MD5Sum< ::pickplace_msgs::AddRemoveObjectsRequest> should match 
// service_traits::MD5Sum< ::pickplace_msgs::AddRemoveObjects > 
template<>
struct MD5Sum< ::pickplace_msgs::AddRemoveObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pickplace_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::AddRemoveObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pickplace_msgs::AddRemoveObjectsRequest> should match 
// service_traits::DataType< ::pickplace_msgs::AddRemoveObjects > 
template<>
struct DataType< ::pickplace_msgs::AddRemoveObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::pickplace_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::AddRemoveObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pickplace_msgs::AddRemoveObjectsResponse> should match 
// service_traits::MD5Sum< ::pickplace_msgs::AddRemoveObjects > 
template<>
struct MD5Sum< ::pickplace_msgs::AddRemoveObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pickplace_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::AddRemoveObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pickplace_msgs::AddRemoveObjectsResponse> should match 
// service_traits::DataType< ::pickplace_msgs::AddRemoveObjects > 
template<>
struct DataType< ::pickplace_msgs::AddRemoveObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::pickplace_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::pickplace_msgs::AddRemoveObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICKPLACE_MSGS_MESSAGE_ADDREMOVEOBJECTS_H
