
classdef AddBoxRequest < ros.Message
    %AddBoxRequest MATLAB implementation of manipulation_msgs/AddBoxRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'manipulation_msgs/AddBoxRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f75dac4ab9ff9c980f1083805af960a8' % The MD5 Checksum of the message definition
        PropertyList = { 'BoxPose' 'InboundBoxName' 'Height' } % List of non-constant message properties
        ROSPropertyList = { 'box_pose' 'inbound_box_name' 'height' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        BoxPose
        InboundBoxName
        Height
    end
    methods
        function set.BoxPose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'AddBoxRequest', 'BoxPose')
            obj.BoxPose = val;
        end
        function set.InboundBoxName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AddBoxRequest', 'InboundBoxName');
            obj.InboundBoxName = char(val);
        end
        function set.Height(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AddBoxRequest', 'Height');
            obj.Height = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.manipulation_msgs.AddBoxRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.manipulation_msgs.AddBoxRequest;
            obj.reload(strObj);
        end
    end
end
