
classdef AddObjectsRequest < ros.Message
    %AddObjectsRequest MATLAB implementation of manipulation_msgs/AddObjectsRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'manipulation_msgs/AddObjectsRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd9463f0128c5814412de7904bb976146' % The MD5 Checksum of the message definition
        PropertyList = { 'AddObjects' 'InboundBoxName' } % List of non-constant message properties
        ROSPropertyList = { 'add_objects' 'inbound_box_name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.manipulation_msgs.Object' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        AddObjects
        InboundBoxName
    end
    methods
        function set.AddObjects(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.manipulation_msgs.Object.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.manipulation_msgs.Object'};
            validateattributes(val, validClasses, validAttributes, 'AddObjectsRequest', 'AddObjects')
            obj.AddObjects = val;
        end
        function set.InboundBoxName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AddObjectsRequest', 'InboundBoxName');
            obj.InboundBoxName = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.manipulation_msgs.AddObjectsRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.manipulation_msgs.AddObjectsRequest;
            obj.reload(strObj);
        end
    end
end
