
classdef ListOfObjectsResponse < ros.Message
    %ListOfObjectsResponse MATLAB implementation of manipulation_msgs/ListOfObjectsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'manipulation_msgs/ListOfObjectsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '40e4d9b5f6e0112bad855c1d374ac612' % The MD5 Checksum of the message definition
        PropertyList = { 'Type' 'Id' 'Box' } % List of non-constant message properties
        ROSPropertyList = { 'type' 'id' 'box' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Type
        Id
        Box
    end
    methods
        function set.Type(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ListOfObjectsResponse', 'Type');
            obj.Type = cell(val);
        end
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ListOfObjectsResponse', 'Id');
            obj.Id = cell(val);
        end
        function set.Box(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ListOfObjectsResponse', 'Box');
            obj.Box = cell(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.manipulation_msgs.ListOfObjectsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.manipulation_msgs.ListOfObjectsResponse;
            obj.reload(strObj);
        end
    end
end
