
classdef AddRemoveObjectsResponse < ros.Message
    %AddRemoveObjectsResponse MATLAB implementation of pickplace_msgs/AddRemoveObjectsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'pickplace_msgs/AddRemoveObjectsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '450796f7fe6bdeb692c1c6881b3b415f' % The MD5 Checksum of the message definition
        PropertyList = { 'Results' } % List of non-constant message properties
        ROSPropertyList = { 'results' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
        Success = int8(0)
        ObjectNotFound = int8(-1)
    end
    properties
        Results
    end
    methods
        function set.Results(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AddRemoveObjectsResponse', 'Results');
            obj.Results = int8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.pickplace_msgs.AddRemoveObjectsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.pickplace_msgs.AddRemoveObjectsResponse;
            obj.reload(strObj);
        end
    end
end
