
classdef Grasp < ros.Message
    %Grasp MATLAB implementation of pickplace_msgs/Grasp
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'pickplace_msgs/Grasp' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6430b0572835c52325dc3518a97c6741' % The MD5 Checksum of the message definition
        PropertyList = { 'Pose' 'ToolName' } % List of non-constant message properties
        ROSPropertyList = { 'pose' 'tool_name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pose
        ToolName
    end
    methods
        function set.Pose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'Grasp', 'Pose')
            obj.Pose = val;
        end
        function set.ToolName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Grasp', 'ToolName');
            obj.ToolName = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.pickplace_msgs.Grasp.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.pickplace_msgs.Grasp;
            obj.reload(strObj);
        end
    end
end
