
classdef ListOfObjectsResponse < ros.Message
    %ListOfObjectsResponse MATLAB implementation of pickplace_msgs/ListOfObjectsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'pickplace_msgs/ListOfObjectsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '0a03ffd681ce57fde2c5f01b0609f939' % The MD5 Checksum of the message definition
        PropertyList = { 'InboundBoxes' } % List of non-constant message properties
        ROSPropertyList = { 'inbound_boxes' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.pickplace_msgs.PickBox' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        InboundBoxes
    end
    methods
        function set.InboundBoxes(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.pickplace_msgs.PickBox.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.pickplace_msgs.PickBox'};
            validateattributes(val, validClasses, validAttributes, 'ListOfObjectsResponse', 'InboundBoxes')
            obj.InboundBoxes = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.pickplace_msgs.ListOfObjectsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.pickplace_msgs.ListOfObjectsResponse;
            obj.reload(strObj);
        end
    end
end
