
classdef Object < ros.Message
    %Object MATLAB implementation of pickplace_msgs/Object
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'pickplace_msgs/Object' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '788dd860139d2161833ce2bcb82fe554' % The MD5 Checksum of the message definition
        PropertyList = { 'GraspingPoses' 'Type' 'Id' } % List of non-constant message properties
        ROSPropertyList = { 'grasping_poses' 'type' 'id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.pickplace_msgs.Grasp' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        GraspingPoses
        Type
        Id
    end
    methods
        function set.GraspingPoses(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.pickplace_msgs.Grasp.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.pickplace_msgs.Grasp'};
            validateattributes(val, validClasses, validAttributes, 'Object', 'GraspingPoses')
            obj.GraspingPoses = val;
        end
        function set.Type(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Object', 'Type');
            obj.Type = char(val);
        end
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Object', 'Id');
            obj.Id = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.pickplace_msgs.Object.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.pickplace_msgs.Object;
            obj.reload(strObj);
        end
    end
end
