
classdef RemoveLocationsRequest < ros.Message
    %RemoveLocationsRequest MATLAB implementation of manipulation_msgs/RemoveLocationsRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'manipulation_msgs/RemoveLocationsRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8c80bdc7cee467e52ed1c783520ee4bb' % The MD5 Checksum of the message definition
        PropertyList = { 'LocationNames' } % List of non-constant message properties
        ROSPropertyList = { 'location_names' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        LocationNames
    end
    methods
        function set.LocationNames(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RemoveLocationsRequest', 'LocationNames');
            obj.LocationNames = cell(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.manipulation_msgs.RemoveLocationsRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.manipulation_msgs.RemoveLocationsRequest;
            obj.reload(strObj);
        end
    end
end
