// Generated by gencpp from file manipulation_msgs/AddBox.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDBOX_H
#define MANIPULATION_MSGS_MESSAGE_ADDBOX_H

#include <ros/service_traits.h>


#include <manipulation_msgs/AddBoxRequest.h>
#include <manipulation_msgs/AddBoxResponse.h>


namespace manipulation_msgs
{

struct AddBox
{

typedef AddBoxRequest Request;
typedef AddBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddBox
} // namespace manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation_msgs::AddBox > {
  static const char* value()
  {
    return "f75dac4ab9ff9c980f1083805af960a8";
  }

  static const char* value(const ::manipulation_msgs::AddBox&) { return value(); }
};

template<>
struct DataType< ::manipulation_msgs::AddBox > {
  static const char* value()
  {
    return "manipulation_msgs/AddBox";
  }

  static const char* value(const ::manipulation_msgs::AddBox&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation_msgs::AddBoxRequest> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddBox > 
template<>
struct MD5Sum< ::manipulation_msgs::AddBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddBox >::value();
  }
  static const char* value(const ::manipulation_msgs::AddBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddBoxRequest> should match 
// service_traits::DataType< ::manipulation_msgs::AddBox > 
template<>
struct DataType< ::manipulation_msgs::AddBoxRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddBox >::value();
  }
  static const char* value(const ::manipulation_msgs::AddBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation_msgs::AddBoxResponse> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddBox > 
template<>
struct MD5Sum< ::manipulation_msgs::AddBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddBox >::value();
  }
  static const char* value(const ::manipulation_msgs::AddBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddBoxResponse> should match 
// service_traits::DataType< ::manipulation_msgs::AddBox > 
template<>
struct DataType< ::manipulation_msgs::AddBoxResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddBox >::value();
  }
  static const char* value(const ::manipulation_msgs::AddBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDBOX_H
