// Generated by gencpp from file manipulation_msgs/AddLocationsRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDLOCATIONSREQUEST_H
#define MANIPULATION_MSGS_MESSAGE_ADDLOCATIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <manipulation_msgs/Location.h>

namespace manipulation_msgs
{
template <class ContainerAllocator>
struct AddLocationsRequest_
{
  typedef AddLocationsRequest_<ContainerAllocator> Type;

  AddLocationsRequest_()
    : locations()  {
    }
  AddLocationsRequest_(const ContainerAllocator& _alloc)
    : locations(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::manipulation_msgs::Location_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::manipulation_msgs::Location_<ContainerAllocator> >::other >  _locations_type;
  _locations_type locations;





  typedef boost::shared_ptr< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddLocationsRequest_

typedef ::manipulation_msgs::AddLocationsRequest_<std::allocator<void> > AddLocationsRequest;

typedef boost::shared_ptr< ::manipulation_msgs::AddLocationsRequest > AddLocationsRequestPtr;
typedef boost::shared_ptr< ::manipulation_msgs::AddLocationsRequest const> AddLocationsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'manipulation_msgs': ['/home/jacobi/projects/ros_ws/src/manipulation/matlab_msg_gen_ros1/glnxa64/src/manipulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b26604672dcaffe33782b1b138fff5";
  }

  static const char* value(const ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b26604672dcaffULL;
  static const uint64_t static_value2 = 0xe33782b1b138fff5ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation_msgs/AddLocationsRequest";
  }

  static const char* value(const ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation_msgs/Location[] locations\n"
"\n"
"================================================================================\n"
"MSG: manipulation_msgs/Location\n"
"string id\n"
"string frame\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Pose approach_relative_pose\n"
"geometry_msgs/Pose return_relative_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.locations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddLocationsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation_msgs::AddLocationsRequest_<ContainerAllocator>& v)
  {
    s << indent << "locations[]" << std::endl;
    for (size_t i = 0; i < v.locations.size(); ++i)
    {
      s << indent << "  locations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::manipulation_msgs::Location_<ContainerAllocator> >::stream(s, indent + "    ", v.locations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDLOCATIONSREQUEST_H
