// Generated by gencpp from file manipulation_msgs/AddLocations.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDLOCATIONS_H
#define MANIPULATION_MSGS_MESSAGE_ADDLOCATIONS_H

#include <ros/service_traits.h>


#include <manipulation_msgs/AddLocationsRequest.h>
#include <manipulation_msgs/AddLocationsResponse.h>


namespace manipulation_msgs
{

struct AddLocations
{

typedef AddLocationsRequest Request;
typedef AddLocationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddLocations
} // namespace manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation_msgs::AddLocations > {
  static const char* value()
  {
    return "89b26604672dcaffe33782b1b138fff5";
  }

  static const char* value(const ::manipulation_msgs::AddLocations&) { return value(); }
};

template<>
struct DataType< ::manipulation_msgs::AddLocations > {
  static const char* value()
  {
    return "manipulation_msgs/AddLocations";
  }

  static const char* value(const ::manipulation_msgs::AddLocations&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation_msgs::AddLocationsRequest> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddLocations > 
template<>
struct MD5Sum< ::manipulation_msgs::AddLocationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddLocations >::value();
  }
  static const char* value(const ::manipulation_msgs::AddLocationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddLocationsRequest> should match 
// service_traits::DataType< ::manipulation_msgs::AddLocations > 
template<>
struct DataType< ::manipulation_msgs::AddLocationsRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddLocations >::value();
  }
  static const char* value(const ::manipulation_msgs::AddLocationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation_msgs::AddLocationsResponse> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddLocations > 
template<>
struct MD5Sum< ::manipulation_msgs::AddLocationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddLocations >::value();
  }
  static const char* value(const ::manipulation_msgs::AddLocationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddLocationsResponse> should match 
// service_traits::DataType< ::manipulation_msgs::AddLocations > 
template<>
struct DataType< ::manipulation_msgs::AddLocationsResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddLocations >::value();
  }
  static const char* value(const ::manipulation_msgs::AddLocationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDLOCATIONS_H
