// Generated by gencpp from file manipulation_msgs/AddObjects.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDOBJECTS_H
#define MANIPULATION_MSGS_MESSAGE_ADDOBJECTS_H

#include <ros/service_traits.h>


#include <manipulation_msgs/AddObjectsRequest.h>
#include <manipulation_msgs/AddObjectsResponse.h>


namespace manipulation_msgs
{

struct AddObjects
{

typedef AddObjectsRequest Request;
typedef AddObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddObjects
} // namespace manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation_msgs::AddObjects > {
  static const char* value()
  {
    return "4321e80b8bf2a31d7203c0e48f1b70be";
  }

  static const char* value(const ::manipulation_msgs::AddObjects&) { return value(); }
};

template<>
struct DataType< ::manipulation_msgs::AddObjects > {
  static const char* value()
  {
    return "manipulation_msgs/AddObjects";
  }

  static const char* value(const ::manipulation_msgs::AddObjects&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation_msgs::AddObjectsRequest> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddObjects > 
template<>
struct MD5Sum< ::manipulation_msgs::AddObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddObjectsRequest> should match 
// service_traits::DataType< ::manipulation_msgs::AddObjects > 
template<>
struct DataType< ::manipulation_msgs::AddObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation_msgs::AddObjectsResponse> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddObjects > 
template<>
struct MD5Sum< ::manipulation_msgs::AddObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddObjectsResponse> should match 
// service_traits::DataType< ::manipulation_msgs::AddObjects > 
template<>
struct DataType< ::manipulation_msgs::AddObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDOBJECTS_H
