// Generated by gencpp from file manipulation_msgs/AddRemoveObjects.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDREMOVEOBJECTS_H
#define MANIPULATION_MSGS_MESSAGE_ADDREMOVEOBJECTS_H

#include <ros/service_traits.h>


#include <manipulation_msgs/AddRemoveObjectsRequest.h>
#include <manipulation_msgs/AddRemoveObjectsResponse.h>


namespace manipulation_msgs
{

struct AddRemoveObjects
{

typedef AddRemoveObjectsRequest Request;
typedef AddRemoveObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddRemoveObjects
} // namespace manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation_msgs::AddRemoveObjects > {
  static const char* value()
  {
    return "6ba7cf8734f51f28c5c0c6aba89a6f3a";
  }

  static const char* value(const ::manipulation_msgs::AddRemoveObjects&) { return value(); }
};

template<>
struct DataType< ::manipulation_msgs::AddRemoveObjects > {
  static const char* value()
  {
    return "manipulation_msgs/AddRemoveObjects";
  }

  static const char* value(const ::manipulation_msgs::AddRemoveObjects&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation_msgs::AddRemoveObjectsRequest> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddRemoveObjects > 
template<>
struct MD5Sum< ::manipulation_msgs::AddRemoveObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddRemoveObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddRemoveObjectsRequest> should match 
// service_traits::DataType< ::manipulation_msgs::AddRemoveObjects > 
template<>
struct DataType< ::manipulation_msgs::AddRemoveObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddRemoveObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation_msgs::AddRemoveObjectsResponse> should match 
// service_traits::MD5Sum< ::manipulation_msgs::AddRemoveObjects > 
template<>
struct MD5Sum< ::manipulation_msgs::AddRemoveObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddRemoveObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::AddRemoveObjectsResponse> should match 
// service_traits::DataType< ::manipulation_msgs::AddRemoveObjects > 
template<>
struct DataType< ::manipulation_msgs::AddRemoveObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::AddRemoveObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::AddRemoveObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDREMOVEOBJECTS_H
