// Generated by gencpp from file manipulation_msgs/AddRemoveObjectsResponse.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_ADDREMOVEOBJECTSRESPONSE_H
#define MANIPULATION_MSGS_MESSAGE_ADDREMOVEOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation_msgs
{
template <class ContainerAllocator>
struct AddRemoveObjectsResponse_
{
  typedef AddRemoveObjectsResponse_<ContainerAllocator> Type;

  AddRemoveObjectsResponse_()
    : results(0)  {
    }
  AddRemoveObjectsResponse_(const ContainerAllocator& _alloc)
    : results(0)  {
  (void)_alloc;
    }



   typedef int8_t _results_type;
  _results_type results;



  enum {
 
    Success = 0,
 
    ObjectNotFound = -1,
  };


  typedef boost::shared_ptr< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddRemoveObjectsResponse_

typedef ::manipulation_msgs::AddRemoveObjectsResponse_<std::allocator<void> > AddRemoveObjectsResponse;

typedef boost::shared_ptr< ::manipulation_msgs::AddRemoveObjectsResponse > AddRemoveObjectsResponsePtr;
typedef boost::shared_ptr< ::manipulation_msgs::AddRemoveObjectsResponse const> AddRemoveObjectsResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'manipulation_msgs': ['/home/jacobi/projects/ros_ws/src/manipulation/matlab_msg_gen_ros1/glnxa64/src/manipulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "450796f7fe6bdeb692c1c6881b3b415f";
  }

  static const char* value(const ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x450796f7fe6bdeb6ULL;
  static const uint64_t static_value2 = 0x92c1c6881b3b415fULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation_msgs/AddRemoveObjectsResponse";
  }

  static const char* value(const ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 results\n"
"int8 Success=0\n"
"int8 ObjectNotFound=-1\n"
"\n"
"\n"
;
  }

  static const char* value(const ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddRemoveObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation_msgs::AddRemoveObjectsResponse_<ContainerAllocator>& v)
  {
    s << indent << "results: ";
    Printer<int8_t>::stream(s, indent + "  ", v.results);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_ADDREMOVEOBJECTSRESPONSE_H
