// Generated by gencpp from file manipulation_msgs/ListOfObjects.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_LISTOFOBJECTS_H
#define MANIPULATION_MSGS_MESSAGE_LISTOFOBJECTS_H

#include <ros/service_traits.h>


#include <manipulation_msgs/ListOfObjectsRequest.h>
#include <manipulation_msgs/ListOfObjectsResponse.h>


namespace manipulation_msgs
{

struct ListOfObjects
{

typedef ListOfObjectsRequest Request;
typedef ListOfObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListOfObjects
} // namespace manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation_msgs::ListOfObjects > {
  static const char* value()
  {
    return "40e4d9b5f6e0112bad855c1d374ac612";
  }

  static const char* value(const ::manipulation_msgs::ListOfObjects&) { return value(); }
};

template<>
struct DataType< ::manipulation_msgs::ListOfObjects > {
  static const char* value()
  {
    return "manipulation_msgs/ListOfObjects";
  }

  static const char* value(const ::manipulation_msgs::ListOfObjects&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation_msgs::ListOfObjectsRequest> should match 
// service_traits::MD5Sum< ::manipulation_msgs::ListOfObjects > 
template<>
struct MD5Sum< ::manipulation_msgs::ListOfObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::ListOfObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::ListOfObjectsRequest> should match 
// service_traits::DataType< ::manipulation_msgs::ListOfObjects > 
template<>
struct DataType< ::manipulation_msgs::ListOfObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::ListOfObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation_msgs::ListOfObjectsResponse> should match 
// service_traits::MD5Sum< ::manipulation_msgs::ListOfObjects > 
template<>
struct MD5Sum< ::manipulation_msgs::ListOfObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::ListOfObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::ListOfObjectsResponse> should match 
// service_traits::DataType< ::manipulation_msgs::ListOfObjects > 
template<>
struct DataType< ::manipulation_msgs::ListOfObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::ListOfObjects >::value();
  }
  static const char* value(const ::manipulation_msgs::ListOfObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_LISTOFOBJECTS_H
