// Generated by gencpp from file manipulation_msgs/RemoveLocationsRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_REMOVELOCATIONSREQUEST_H
#define MANIPULATION_MSGS_MESSAGE_REMOVELOCATIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation_msgs
{
template <class ContainerAllocator>
struct RemoveLocationsRequest_
{
  typedef RemoveLocationsRequest_<ContainerAllocator> Type;

  RemoveLocationsRequest_()
    : location_names()  {
    }
  RemoveLocationsRequest_(const ContainerAllocator& _alloc)
    : location_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _location_names_type;
  _location_names_type location_names;





  typedef boost::shared_ptr< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveLocationsRequest_

typedef ::manipulation_msgs::RemoveLocationsRequest_<std::allocator<void> > RemoveLocationsRequest;

typedef boost::shared_ptr< ::manipulation_msgs::RemoveLocationsRequest > RemoveLocationsRequestPtr;
typedef boost::shared_ptr< ::manipulation_msgs::RemoveLocationsRequest const> RemoveLocationsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'manipulation_msgs': ['/home/jacobi/projects/ros_ws/src/manipulation/matlab_msg_gen_ros1/glnxa64/src/manipulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c80bdc7cee467e52ed1c783520ee4bb";
  }

  static const char* value(const ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c80bdc7cee467e5ULL;
  static const uint64_t static_value2 = 0x2ed1c783520ee4bbULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation_msgs/RemoveLocationsRequest";
  }

  static const char* value(const ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] location_names\n"
;
  }

  static const char* value(const ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveLocationsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation_msgs::RemoveLocationsRequest_<ContainerAllocator>& v)
  {
    s << indent << "location_names[]" << std::endl;
    for (size_t i = 0; i < v.location_names.size(); ++i)
    {
      s << indent << "  location_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_REMOVELOCATIONSREQUEST_H
